# -*- coding: utf-8 -*-
"""
Packs the sheet CSVs into one .xlsx with five tabs, ready to drop into the
Google Sheet in a single import.

    python3 src/prep/make_workbook.py

In Google Sheets:  File > Import > Upload > (this file) > "Insert new sheet(s)"

Tab names must match TABS below -- the build fetches each tab by name, not by
gid, so tabs survive being deleted and recreated.
"""
import csv, os, sys
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SHEETS = os.path.join(ROOT, "sheets")
OUT = os.path.join(ROOT, "Medicines-by-class.xlsx")

# csv file -> tab name (the build reads these tab names)
TABS = [
    ("01_classes.csv",       "classes"),
    ("02_medicines.csv",     "medicines"),
    ("03_class_content.csv", "content"),
    ("04_faqs.csv",          "faqs"),
    ("05_redirects.csv",     "redirects"),
]

# columns a human is expected to edit, highlighted so the generated ones are
# visibly distinct from the ones a catalogue refresh will overwrite
EDITABLE = {
    "classes":   {"class_name", "h1_override", "short_desc", "is_popular",
                  "popular_rank", "synonyms", "related_class_ids", "status",
                  "redirect_to", "sitemap_priority", "conditions"},
    "medicines": {"sort_rank", "status"},
    "content":   {"meta_title", "meta_description", "intro_md", "about_heading",
                  "about_md", "subclass_heading", "subclass_md",
                  "prescription_heading", "prescription_md", "safety_bullets_md",
                  "reviewer_name", "reviewer_credentials", "reviewer_profile_url",
                  "medically_reviewed_on", "content_last_updated",
                  "canonical_override", "noindex", "content_status"},
    "faqs":      {"question", "answer_md", "status", "position"},
    "redirects": {"from_path", "to_path", "status_code", "note"},
}

HEAD_GEN  = PatternFill("solid", fgColor="E6E9ED")   # generated -> grey
HEAD_EDIT = PatternFill("solid", fgColor="E6F3F2")   # editable  -> teal tint

wb = Workbook()
wb.remove(wb.active)

for fname, tab in TABS:
    path = os.path.join(SHEETS, fname)
    if not os.path.exists(path):
        print(f"  skip {fname} (missing)")
        continue

    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    if not rows:
        continue
    head, body = rows[0], rows[1:]

    ws = wb.create_sheet(tab)
    ws.append(head)
    for r in body:
        # keep everything as text: product ids and pack sizes must not be
        # coerced into numbers or dates by Sheets on import
        ws.append([("'" + c if c and (c[0] == "=" or c[0] == "+") else c) for c in r])

    editable = EDITABLE.get(tab, set())
    for i, col in enumerate(head, start=1):
        cell = ws.cell(row=1, column=i)
        cell.font = Font(bold=True, size=10)
        cell.fill = HEAD_EDIT if col in editable else HEAD_GEN
        cell.alignment = Alignment(vertical="center")
        width = max(len(col) + 2, min(46, max((len(r[i - 1]) for r in body[:200] if len(r) >= i), default=10) + 2))
        ws.column_dimensions[get_column_letter(i)].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(head))}{len(body) + 1}"
    print(f"  {tab:12} {len(body):>5,} rows  {len(head)} cols")

# a short read-me tab so anyone opening the sheet knows the rules
ws = wb.create_sheet("_README", 0)
for line in [
    ["Medicines by Class – source of truth"],
    [],
    ["Tab", "What it controls", "Safe to edit?"],
    ["classes", "Class pages, names, icons, popular grid, synonyms + condition search terms", "Yes – teal columns"],
    ["medicines", "Which medicines appear under each class", "Regenerated from the catalogue dump – edit sort_rank/status only"],
    ["content", "All page copy, meta, reviewer, publish state", "Yes – this is the editorial tab"],
    ["faqs", "One row per question; feeds the FAQ accordion and FAQPage schema", "Yes"],
    ["redirects", "Old path -> new path when a slug changes", "Yes"],
    [],
    ["Rules"],
    ["1", "Never edit class_id or sku – they are the join keys. Change slug instead; add a redirects row."],
    ["2", "Copy rule: 'used for' / 'used in the management of'. Never 'cures', 'treats', 'best', 'safest'."],
    ["3", "content_status=published requires reviewer_name to be filled, or the build fails."],
    ["4", "Grey headers are generated by the pipeline and will be overwritten on a catalogue refresh."],
    ["5", "The build validates this sheet before publishing. A bad cell fails the build, it does not ship."],
    ["6", "conditions = pipe-separated everyday words (fever|cold|acidity). Drives search + the best-match banner."],
] :
    ws.append(line)
ws["A1"].font = Font(bold=True, size=14)
for c in ("A3", "B3", "C3"):
    ws[c].font = Font(bold=True)
    ws[c].fill = HEAD_GEN
ws["A10"].font = Font(bold=True)
ws.column_dimensions["A"].width = 14
ws.column_dimensions["B"].width = 78
ws.column_dimensions["C"].width = 62

wb.save(OUT)
print(f"\nwrote {os.path.relpath(OUT, ROOT)}  ({os.path.getsize(OUT) / 1024:.0f} KB)")
print("Google Sheets:  File > Import > Upload > Insert new sheet(s)")
